use std::cell::{OnceCell, RefCell};

thread_local! {
  pub(crate) static RUNTIME: RefCell<OnceCell<crate::Runtime>> = RefCell::new(OnceCell::new());
}

pub fn setup(options: crate::runtime::RuntimeOptions) {
  RUNTIME.with(|rt| {
    if let Some(_) = rt.borrow().get() {
      return;
    }
    rt.borrow_mut().set(crate::Runtime::new(options)).unwrap();
  });
}

pub fn dispose() {
  if let Some(rt) = RUNTIME.take().take() {
    drop(unsafe { Box::from_raw(rt.data) });
  }
}

pub fn write_blob() {
  crate::prelude::RUNTIME.take().take().unwrap().write_blob();
}

#[macro_export]
macro_rules! startup {
  ($main:path, snapshot = true) => {
    fn main() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
      runtime::init();

      runtime::prelude::setup(runtime::RuntimeOptions::SnapshotCreator);
      // let result = tokio::runtime::Builder::new_multi_thread()
      //   .on_thread_start(|| runtime::prelude::setup())
      let result = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .unwrap()
        .block_on({ $main() });

      runtime::prelude::dispose();
      runtime::dispose();

      return result;
    }
  };
  ($main:path, blob = $blob_path:expr) => {
    // Load the snapshot generated by build.rs:
    static RUNTIME_SNAPSHOT: &[u8] = include_bytes!($blob_path);

    fn main() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
      runtime::init();

      runtime::prelude::setup(runtime::RuntimeOptions::FromBlob(RUNTIME_SNAPSHOT));
      // let result = tokio::runtime::Builder::new_multi_thread()
      //   .on_thread_start(|| runtime::prelude::setup())
      let result = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .unwrap()
        .block_on({ $main() });

      runtime::prelude::dispose();
      runtime::dispose();

      return result;
    }
  };
  ($main:path) => {
    fn main() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
      runtime::init();

      runtime::prelude::setup(runtime::RuntimeOptions::Default);
      // let result = tokio::runtime::Builder::new_multi_thread()
      //   .on_thread_start(|| runtime::prelude::setup())
      let result = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .unwrap()
        .block_on({ $main() });

      runtime::prelude::dispose();
      runtime::dispose();

      return result;
    }
  };
}
